# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CS130Project' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CS130Project

  target 'CS130ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CS130ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
